apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: runoncedurationoverride-scc-hostnetwork-use
  namespace: run-once-duration-override
rules:
  - apiGroups:
      - security.openshift.io
    resources:
      - securitycontextconstraints
    verbs:
      - use
    resourceNames:
      - hostnetwork
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: runoncedurationoverride-scc-hostnetwork-use
  namespace: run-once-duration-override
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: runoncedurationoverride-scc-hostnetwork-use
subjects:
  - kind: ServiceAccount
    namespace: run-once-duration-override
    name: runoncedurationoverride
