apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: runoncedurationoverrides.admission.runoncedurationoverride.openshift.io
  labels:
    runoncedurationoverride: "true"
webhooks:
  - name: runoncedurationoverrides.admission.runoncedurationoverride.openshift.io
    namespaceSelector:
      matchLabels:
        runoncedurationoverrides.admission.runoncedurationoverride.openshift.io/enabled: "true"
      matchExpressions:
        - key: runlevel
          operator: NotIn
          values: ["0","1"]
    matchPolicy: Equivalent
    clientConfig:
      url: https://localhost:9400/apis/admission.runoncedurationoverride.openshift.io/v1/runoncedurationoverrides
      caBundle: SERVICE_SERVING_CERT_CA
    rules:
      - operations:
          - CREATE
          - UPDATE
        apiGroups:
          - ""
        apiVersions:
          - "v1"
        resources:
          - "pods"
        scope: "Namespaced"
    failurePolicy: Fail
    timeoutSeconds: 5
    sideEffects: None
    reinvocationPolicy: IfNeeded
    admissionReviewVersions: ["v1", "v1beta1"]
